version: 0.2

env:
  parameter-store:
    GITHUB_SSH_KEY: tooda-submodule-ssh-key


phases:
  pre_build:
    commands:
      - echo Pooling Git Submodules...
      - mkdir -p ~/.ssh
      - echo "$GITHUB_SSH_KEY" > ~/.ssh/id_rsa
      - chmod 600 ~/.ssh/id_rsa
      - ssh-keygen -F github.com || ssh-keyscan github.com >>~/.ssh/known_hosts
      - git config --global url."git@github.com:".insteadOf "https://github.com/"
      - git init
      - git remote add origin git@github.com:jabonge/tooda-secret.git
      - git fetch
      - git submodule init
      - git submodule update --recursive
      - echo Logging in to Amazon ECR...
      - aws ecr get-login-password --region $AWS_DEFAULT_REGION | docker login --username AWS --password-stdin $AWS_ACCOUNT_ID.dkr.ecr.$AWS_DEFAULT_REGION.amazonaws.com
  build:
    commands:
      - echo Build started on `date`
      - echo Gradle build
      - chmod +x ./gradlew
      - ./gradlew build --exclude-task test
  post_build:
    commands:
      - echo Building the Docker image and Pushing ECR...
      - echo $(basename ./build/libs/*.jar)
      - docker build -t $IMAGE_REPO_NAME:$IMAGE_TAG .
      - docker tag $IMAGE_REPO_NAME:$IMAGE_TAG $AWS_ACCOUNT_ID.dkr.ecr.$AWS_DEFAULT_REGION.amazonaws.com/$IMAGE_REPO_NAME:$IMAGE_TAG
      - docker push $AWS_ACCOUNT_ID.dkr.ecr.$AWS_DEFAULT_REGION.amazonaws.com/$IMAGE_REPO_NAME:$IMAGE_TAG

artifacts:
  files:
    - appspec.yml
    - script/**
    - docker-compose.yml
  discard-paths: yes

cache:
  paths:
    - '/root/.gradle/caches/**/*'

