version: '3.1'

services:
  db:
    image: mysql
    container_name: tooda_database
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: tooda!
    volumes:
      - ./docker/db:/var/lib/mysql
    ports:
      - "3306:3306"
  app:
    container_name: tooda_spring
    build:
      dockerfile: Dockerfile
      context: ./
    ports:
      - "8080:8080"
    depends_on:
      - db