spring:
  profiles:
    include: security
  h2:
    console:
      enabled: true
  mvc:
    throw-exception-if-no-handler-found: true
    dispatch-options-request: false

  datasource:
    url: jdbc:h2:mem:test
    driver-class-name: org.h2.Driver
    username: sa
    password:

  jpa:
    show-sql: true
    hibernate:
      format-sql: true
      ddl-auto: create-drop
      naming:
        physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
    defer-datasource-initialization: true



