spring:
  profiles:
    include: security
  h2:
    console:
      enabled: true

  datasource:
    url: jdbc:h2:mem:test
    driver-class-name: org.h2.Driver
    username: sa
    password:

  jpa:
    show-sql: true
    ddl-auto: create-drop
    properties:
      hibernate:
        format-sql: true


