spring:
  profiles:
    include: security, database, aws
    group:
      dev: dev, common
      prod: prod, common
      local: local, common

---
spring:
  config:
    activate:
      on-profile: common
  mvc:
    throw-exception-if-no-handler-found: true
  web:
    resources:
      add-mappings: false
  servlet:
    multipart:
      max-file-size: 20MB
      max-request-size: 20MB


